name: Injectable

on:
  pull_request:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Vulnerable
        run: echo "Title is ${{ github.event.pull_request.title }}"
      - name: Safe
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: echo "Title is $TITLE"